AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'spec/models/**/*'
Metrics/BlockLength:
  Max: 50
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: False
Metrics/MethodLength:
  Max: 15
