AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'spec/models/case_stat_spec.rb'
    - 'spec/models/court_case_spec.rb'
    - 'spec/models/offense_code_spec.rb'
    - 'spec/models/party_stat_spec.rb'
    - 'spec/models/report_searchable_case_spec.rb'
    - 'vendor/**/*'
Metrics/BlockLength:
  Max: 50
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/models/**/*'
Style/CaseEquality:
  AllowOnConstant: true
Metrics/AbcSize:
  Enabled: false
