AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Metrics/BlockLength:
  Max: 50
