module CaseInfo
  CASE_TYPES = [
    { oscn_id: 35, abbreviation: 'AI', name: 'ARTIFICIAL INSEMINATIONS' },
    { oscn_id: 60, abbreviation: 'AM', name: 'ANNA MCBRIDE ACT - MENTAL HEALTH COURT' },
    { oscn_id: 61, abbreviation: 'AO', name: 'CIVIL ADMINISTRATIVE' },
    { oscn_id: 53, abbreviation: 'BI', name: 'BINGO LICENSE (LEGACY)' },
    { oscn_id: 62, abbreviation: 'BL', name: 'BONDSMAN LICENSE' },
    { oscn_id: 29, abbreviation: 'BV', name: 'BEVERAGE LICENSE' },
    { oscn_id: 63, abbreviation: 'CA', name: 'COST ADMINISTRATION' },
    { oscn_id: 51, abbreviation: 'CA', name: 'CIVIL ADMINISTRATIVE (LEGACY)' },
    { oscn_id: 59, abbreviation: 'CCA', name: 'CREDIT CARD ADJUSTMENT' },
    { oscn_id: 31, abbreviation: 'CF', name: 'CRIMINAL FELONY' },
    { oscn_id: 2, abbreviation: 'CJ', name: 'CIVIL RELIEF MORE THAN $10,000' },
    { oscn_id: 52, abbreviation: 'CJX', name: 'CIVIL MISC. CONVERSION (LEGACY)' },
    { oscn_id: 32, abbreviation: 'CM', name: 'CRIMINAL MISDEMEANOR' },
    { oscn_id: 21, abbreviation: 'CO', name: 'CLOSING OUT SALE' },
    { oscn_id: 40, abbreviation: 'CP', name: 'CRIMINAL PROPERTY RECOVERY' },
    { oscn_id: 64, abbreviation: 'CPC', name: 'CRIMINAL PROBABLE CAUSE' },
    { oscn_id: 1, abbreviation: 'CS', name: 'CIVIL RELIEF LESS THAN $10,000' },
    { oscn_id: 22, abbreviation: 'CV', name: 'CIVIL MISC.' },
    { oscn_id: 65, abbreviation: 'DC', name: 'DRUG COURT' },
    { oscn_id: 66, abbreviation: 'DTR', name: 'DECLINED TRAFFIC TICKETS' },
    { oscn_id: 11, abbreviation: 'FA', name: 'ADOPTION' },
    { oscn_id: 67, abbreviation: 'FB', name: 'FULL BLOOD PROCEEDINGS' },
    { oscn_id: 3, abbreviation: 'FD', name: 'FAMILY AND DOMESTIC' },
    { oscn_id: 6, abbreviation: 'FI', name: 'INCOME ASSIGNMENT' },
    { oscn_id: 68, abbreviation: 'FMI', name: 'FAMILY AND DOMESTIC MISCELLANEOUS PROCEEDINGS' },
    { oscn_id: 5, abbreviation: 'FP', name: 'PATERNITY' },
    { oscn_id: 4, abbreviation: 'FR', name: 'RECIPROCAL CHILD SUPPORT' },
    { oscn_id: 42, abbreviation: 'FS', name: 'FOREIGN SERVICE SERVER (LEGACY)' },
    { oscn_id: 69, abbreviation: 'GJ', name: 'GRAND JURY/MULTICOUNTY GRAND JURY' },
    { oscn_id: 14, abbreviation: 'JD', name: 'JUVENILE DEPRIVED' },
    { oscn_id: 55, abbreviation: 'JDH', name: 'JUVENILE SHOW CAUSE HEARING' },
    { oscn_id: 56, abbreviation: 'JDHT', name: 'JUVENILE MENTAL HEALTH' },
    { oscn_id: 17, abbreviation: 'JDL', name: 'JUVENILE DELINQUENT' },
    { oscn_id: 70, abbreviation: 'JDLH', name: 'JUVENILE DELINQUENT SHOW CAUSE HEARING' },
    { oscn_id: 54, abbreviation: 'JMI', name: 'JUVENILE MISCELLANEOUS' },
    { oscn_id: 58, abbreviation: 'JNF', name: 'JUVENILE NOT FILED (LEGACY)' },
    { oscn_id: 15, abbreviation: 'JS', name: 'JUVENILE IN NEED OF SUPERVISION' },
    { oscn_id: 16, abbreviation: 'JT', name: 'JUVENILE IN NEED OF TREATMENT' },
    { oscn_id: 57, abbreviation: 'JU', name: 'JUVENILE (LEGACY)' },
    { oscn_id: 71, abbreviation: 'MC', name: "MINISTER'S CREDENTIALS" },
    { oscn_id: 12, abbreviation: 'MH', name: 'MENTAL HEALTH' },
    { oscn_id: 33, abbreviation: 'MI', name: 'CRIMINAL MISCELLANEOUS' },
    { oscn_id: 28, abbreviation: 'ML', name: 'MARRIAGE LICENSE' },
    { oscn_id: 72, abbreviation: 'MR', name: 'MISCELLANEOUS RECEIPTS' },
    { oscn_id: 73, abbreviation: 'MRC', name: 'MISCELLANEOUS RECEIPTS - CRIMINAL' },
    { oscn_id: 74, abbreviation: 'MRCV', name: 'MISCELLANEOUS RECEIPTS - CIVIL' },
    { oscn_id: 75, abbreviation: 'MRFD', name: 'MISCELLANEOUS RECEIPTS - FAMILY DOMESTIC' },
    { oscn_id: 76, abbreviation: 'MRPB', name: 'MISCELLANEOUS RECEIPTS - PROBATE' },
    { oscn_id: 77, abbreviation: 'MRSC', name: 'MISCELLANEOUS RECEIPTS - SMALL CLAIMS' },
    { oscn_id: 36, abbreviation: 'NF', name: 'NOT FILED (CRIMINAL)' },
    { oscn_id: 41, abbreviation: 'NP', name: 'NOTARY PUBLIC (LEGACY)' },
    { oscn_id: 44, abbreviation: 'PA', name: 'PASSPORTS (LEGACY)' },
    { oscn_id: 7, abbreviation: 'PB', name: 'PROBATE' },
    { oscn_id: 9, abbreviation: 'PC', name: 'CONSERVATORSHIPS' },
    { oscn_id: 8, abbreviation: 'PG', name: 'GUARDIANSHIPS' },
    { oscn_id: 39, abbreviation: 'PH', name: 'POOL HALL' },
    { oscn_id: 13, abbreviation: 'PM', name: 'PROBATE, MISC. (LEGACY)' },
    { oscn_id: 78, abbreviation: 'PMI', name: 'PROBATE MISCELLANEOUS PROCEEDINGS' },
    { oscn_id: 34, abbreviation: 'PO', name: 'PROTECTIVE ORDER' },
    { oscn_id: 79, abbreviation: 'PP', name: 'PASSPORTS' },
    { oscn_id: 25, abbreviation: 'PS', name: 'PROCESS SERVER (LEGACY)' },
    { oscn_id: 38, abbreviation: 'PSE', name: 'PROTECTIVE SERVICES TO THE ELDERLY (LEGACY)' },
    { oscn_id: 24, abbreviation: 'PSS', name: 'PROCESS SERVER STATE' },
    { oscn_id: 10, abbreviation: 'PT', name: 'TRUSTS' },
    { oscn_id: 37, abbreviation: 'SB', name: 'STATUTORY BONDS (LEGACY)' },
    { oscn_id: 26, abbreviation: 'SC', name: 'SMALL CLAIMS' },
    { oscn_id: 23, abbreviation: 'SD', name: 'SURFACE DAMAGE' },
    { oscn_id: 19, abbreviation: 'SW', name: 'SEARCH WARRANT' },
    { oscn_id: 49, abbreviation: 'TC', name: 'TEST CASE' },
    { oscn_id: 43, abbreviation: 'TL', name: 'TAX LIENS' },
    { oscn_id: 80, abbreviation: 'TM', name: 'TRANSIENT MERCHANT LICENSE' },
    { oscn_id: 18, abbreviation: 'TR', name: 'TRAFFIC' },
    { oscn_id: 50, abbreviation: 'TRI', name: 'TRAFFIC- FILED BY INFORMATION (LEGACY)' },
    { oscn_id: 30, abbreviation: 'WH', name: 'WRIT (HABEAS)' },
    { oscn_id: 81, abbreviation: 'WIL', name: 'FILING OF WILLS' },
    { oscn_id: 20, abbreviation: 'WL', name: 'WILDLIFE' },
    { oscn_id: 82, abbreviation: 'YO', name: 'YOUTHFUL OFFENDER' }
  ]

  COUNTIES = [
    { name: 'Adair', fips_code: '001' },
    { name: 'Alfalfa', fips_code: '003' },
    { name: 'Atoka', fips_code: '005' },
    { name: 'Beaver', fips_code: '007' },
    { name: 'Beckham', fips_code: '009' },
    { name: 'Blaine', fips_code: '011' },
    { name: 'Bryan', fips_code: '013' },
    { name: 'Caddo', fips_code: '015' },
    { name: 'Canadian', fips_code: '017' },
    { name: 'Carter', fips_code: '019' },
    { name: 'Cherokee', fips_code: '021' },
    { name: 'Choctaw', fips_code: '023' },
    { name: 'Cimarron', fips_code: '025' },
    { name: 'Cleveland', fips_code: '027' },
    { name: 'Coal', fips_code: '029' },
    { name: 'Comanche', fips_code: '031' },
    { name: 'Cotton', fips_code: '033' },
    { name: 'Craig', fips_code: '035' },
    { name: 'Creek', fips_code: '037' },
    { name: 'Custer', fips_code: '039' },
    { name: 'Delaware', fips_code: '041' },
    { name: 'Dewey', fips_code: '043' },
    { name: 'Ellis', fips_code: '045' },
    { name: 'Garfield', fips_code: '047' },
    { name: 'Garvin', fips_code: '049' },
    { name: 'Grady', fips_code: '051' },
    { name: 'Grant', fips_code: '053' },
    { name: 'Greer', fips_code: '055' },
    { name: 'Harmon', fips_code: '057' },
    { name: 'Harper', fips_code: '059' },
    { name: 'Haskell', fips_code: '061' },
    { name: 'Hughes', fips_code: '063' },
    { name: 'Jackson', fips_code: '065' },
    { name: 'Jefferson', fips_code: '067' },
    { name: 'Johnston', fips_code: '069' },
    { name: 'Kay', fips_code: '071' },
    { name: 'Kingfisher', fips_code: '073' },
    { name: 'Kiowa', fips_code: '075' },
    { name: 'Latimer', fips_code: '077' },
    { name: 'Le Flore', fips_code: '079' },
    { name: 'Lincoln', fips_code: '081' },
    { name: 'Logan', fips_code: '083' },
    { name: 'Love', fips_code: '085' },
    { name: 'Major', fips_code: '093' },
    { name: 'Marshall', fips_code: '095' },
    { name: 'Mayes', fips_code: '097' },
    { name: 'McClain', fips_code: '087' },
    { name: 'McCurtain', fips_code: '089' },
    { name: 'McIntosh', fips_code: '091' },
    { name: 'Murray', fips_code: '099' },
    { name: 'Muskogee', fips_code: '101' },
    { name: 'Noble', fips_code: '103' },
    { name: 'Nowata', fips_code: '105' },
    { name: 'Okfuskee', fips_code: '107' },
    { name: 'Oklahoma', fips_code: '109' },
    { name: 'Okmulgee', fips_code: '111' },
    { name: 'Osage', fips_code: '113' },
    { name: 'Ottawa', fips_code: '115' },
    { name: 'Pawnee', fips_code: '117' },
    { name: 'Payne', fips_code: '119' },
    { name: 'Pittsburg', fips_code: '121' },
    { name: 'Pontotoc', fips_code: '123' },
    { name: 'Pottawatomie', fips_code: '125' },
    { name: 'Pushmataha', fips_code: '127' },
    { name: 'Roger Mills', fips_code: '129' },
    { name: 'Rogers', fips_code: '131' },
    { name: 'Seminole', fips_code: '133' },
    { name: 'Sequoyah', fips_code: '135' },
    { name: 'Stephens', fips_code: '137' },
    { name: 'Texas', fips_code: '139' },
    { name: 'Tillman', fips_code: '141' },
    { name: 'Tulsa', fips_code: '143' },
    { name: 'Wagoner', fips_code: '145' },
    { name: 'Washington', fips_code: '147' },
    { name: 'Washita', fips_code: '149' },
    { name: 'Woods', fips_code: '151' },
    { name: 'Woodward', fips_code: '153' }
  ]

  titles = [
    { code: '1', name: 'Abstracting' },
    { code: '2', name: 'Agriculture' },
    { code: '3', name: 'Aircraft and Airports' },
    { code: '3A', name: 'Amusements and Sports' },
    { code: '4', name: 'Animals' },
    { code: '5', name: 'Attorneys and the State Bar' },
    { code: '6', name: 'Banks and Trust Companies' },
    { code: '7', name: 'Blind Persons' },
    { code: '8', name: 'Cemeteries' },
    { code: '9', name: 'Census' },
    { code: '10', name: 'Children' },
    { code: '10A', name: 'Children and Juvenile Code' },
    { code: '11', name: 'Cities and Towns' },
    { code: '12', name: 'Civil Procedure' },
    { code: '12A', name: 'Uniform Commercial Code' },
    { code: '13', name: 'Common Carriers' },
    { code: '14', name: 'Congressional and Legislative Districts' },
    { code: '14A', name: 'Consumer Credit Code' },
    { code: '15', name: 'Contracts' },
    { code: '16', name: 'Conveyances' },
    { code: '17', name: 'Corporation Commission' },
    { code: '18', name: 'Corporations' },
    { code: '19', name: 'Counties and County Officers' },
    { code: '20', name: 'Courts' },
    { code: '21', name: 'Crimes and Punishments' },
    { code: '22', name: 'Criminal Procedure' },
    { code: '23', name: 'Damages' },
    { code: '24', name: 'Debtor and Creditor' },
    { code: '25', name: 'Definitions and General Provisions' },
    { code: '26', name: 'Elections' },
    { code: '27', name: 'Eminent Domain' },
    { code: '27A', name: 'Environment and Natural Resources' },
    { code: '28', name: 'Fees' },
    { code: '29', name: 'Game and Fish' },
    { code: '30', name: 'Guardian and Ward' },
    { code: '31', name: 'Homestead and Exemptions' },
    { code: '32', name: 'Husband and Wife' },
    { code: '33', name: 'Inebriates' },
    { code: '34', name: 'Initiative and Referendum' },
    { code: '35', name: 'Insane and Feeble Minded Persons' },
    { code: '36', name: 'Insurance' },
    { code: '37', name: 'Intoxicating Liquors' },
    { code: '37A', name: 'Alcoholic Beverages' },
    { code: '38', name: 'Jurors' },
    { code: '39', name: 'Justices and Constables' },
    { code: '40', name: 'Labor' },
    { code: '41', name: 'Landlord and Tenant' },
    { code: '42', name: 'Liens' },
    { code: '43', name: 'Marriage' },
    { code: '43A', name: 'Mental Health' },
    { code: '44', name: 'Militia' },
    { code: '45', name: 'Mines and Mining' },
    { code: '46', name: 'Mortgages' },
    { code: '47', name: 'Motor Vehicles' },
    { code: '48', name: 'Negotiable Instruments' },
    { code: '49', name: 'Notaries Public' },
    { code: '50', name: 'Nuisances' },
    { code: '51', name: 'Officers' },
    { code: '52', name: 'Oil and Gas' },
    { code: '53', name: 'Oklahoma Historical Societies and Associations' },
    { code: '54', name: 'Partnership' },
    { code: '55', name: 'Pledges' },
    { code: '56', name: 'Poor Persons' },
    { code: '57', name: 'Prisons and Reformatories' },
    { code: '58', name: 'Probate Procedure' },
    { code: '59', name: 'Professions and Occupations' },
    { code: '60', name: 'Property' },
    { code: '61', name: 'Public Buildings and Public Works' },
    { code: '62', name: 'Public Finance' },
    { code: '63', name: 'Public Health and Safety' },
    { code: '64', name: 'Public Lands' },
    { code: '65', name: 'Public Libraries' },
    { code: '66', name: 'Railroads' },
    { code: '67', name: 'Records' },
    { code: '68', name: 'Revenue and Taxation' },
    { code: '69', name: 'Roads, Bridges, and Ferries' },
    { code: '70', name: 'Schools' },
    { code: '71', name: 'Securities' },
    { code: '72', name: 'Soldiers and Sailors' },
    { code: '73', name: 'State Capital and Capitol Building' },
    { code: '74', name: 'State Government' },
    { code: '75', name: 'Statutes and Reports' },
    { code: '76', name: 'Torts' },
    { code: '77', name: 'Townships and Township Officers' },
    { code: '78', name: 'Trade Marks and Labels' },
    { code: '79', name: 'Trusts and Pools' },
    { code: '80', name: 'United States' },
    { code: '81', name: 'Warehouses' },
    { code: '82', name: 'Waters and Water Rights' },
    { code: '83', name: 'Weights and Measures' },
    { code: '84', name: 'Wills and Succession' },
    { code: '85', name: "Workers' Compensation" },
    { code: '85A', name: "Workers' Compensation" }
  ]
end
