case_types = [
  { oscn_id: 35, abbreviation: 'AI', name: 'ARTIFICIAL INSEMINATIONS' },
  { oscn_id: 60, abbreviation: 'AM', name: 'ANNA MCBRIDE ACT - MENTAL HEALTH COURT' },
  { oscn_id: 61, abbreviation: 'AO', name: 'CIVIL ADMINISTRATIVE' },
  { oscn_id: 53, abbreviation: 'BI', name: 'BINGO LICENSE (LEGACY)' },
  { oscn_id: 62, abbreviation: 'BL', name: 'BONDSMAN LICENSE' },
  { oscn_id: 29, abbreviation: 'BV', name: 'BEVERAGE LICENSE' },
  { oscn_id: 63, abbreviation: 'CA', name: 'COST ADMINISTRATION' },
  { oscn_id: 51, abbreviation: 'CA', name: 'CIVIL ADMINISTRATIVE (LEGACY)' },
  { oscn_id: 59, abbreviation: 'CCA', name: 'CREDIT CARD ADJUSTMENT' },
  { oscn_id: 31, abbreviation: 'CF', name: 'CRIMINAL FELONY' },
  { oscn_id: 2, abbreviation: 'CJ', name: 'CIVIL RELIEF MORE THAN $10,000' },
  { oscn_id: 52, abbreviation: 'CJX', name: 'CIVIL MISC. CONVERSION (LEGACY)' },
  { oscn_id: 32, abbreviation: 'CM', name: 'CRIMINAL MISDEMEANOR' },
  { oscn_id: 21, abbreviation: 'CO', name: 'CLOSING OUT SALE' },
  { oscn_id: 40, abbreviation: 'CP', name: 'CRIMINAL PROPERTY RECOVERY' },
  { oscn_id: 64, abbreviation: 'CPC', name: 'CRIMINAL PROBABLE CAUSE' },
  { oscn_id: 1, abbreviation: 'CS', name: 'CIVIL RELIEF LESS THAN $10,000' },
  { oscn_id: 22, abbreviation: 'CV', name: 'CIVIL MISC.' },
  { oscn_id: 65, abbreviation: 'DC', name: 'DRUG COURT' },
  { oscn_id: 66, abbreviation: 'DTR', name: 'DECLINED TRAFFIC TICKETS' },
  { oscn_id: 11, abbreviation: 'FA', name: 'ADOPTION' },
  { oscn_id: 67, abbreviation: 'FB', name: 'FULL BLOOD PROCEEDINGS' },
  { oscn_id: 3, abbreviation: 'FD', name: 'FAMILY AND DOMESTIC' },
  { oscn_id: 6, abbreviation: 'FI', name: 'INCOME ASSIGNMENT' },
  { oscn_id: 68, abbreviation: 'FMI', name: 'FAMILY AND DOMESTIC MISCELLANEOUS PROCEEDINGS' },
  { oscn_id: 5, abbreviation: 'FP', name: 'PATERNITY' },
  { oscn_id: 4, abbreviation: 'FR', name: 'RECIPROCAL CHILD SUPPORT' },
  { oscn_id: 42, abbreviation: 'FS', name: 'FOREIGN SERVICE SERVER (LEGACY)' },
  { oscn_id: 69, abbreviation: 'GJ', name: 'GRAND JURY/MULTICOUNTY GRAND JURY' },
  { oscn_id: 14, abbreviation: 'JD', name: 'JUVENILE DEPRIVED' },
  { oscn_id: 55, abbreviation: 'JDH', name: 'JUVENILE SHOW CAUSE HEARING' },
  { oscn_id: 56, abbreviation: 'JDHT', name: 'JUVENILE MENTAL HEALTH' },
  { oscn_id: 17, abbreviation: 'JDL', name: 'JUVENILE DELINQUENT' },
  { oscn_id: 70, abbreviation: 'JDLH', name: 'JUVENILE DELINQUENT SHOW CAUSE HEARING' },
  { oscn_id: 54, abbreviation: 'JMI', name: 'JUVENILE MISCELLANEOUS' },
  { oscn_id: 58, abbreviation: 'JNF', name: 'JUVENILE NOT FILED (LEGACY)' },
  { oscn_id: 15, abbreviation: 'JS', name: 'JUVENILE IN NEED OF SUPERVISION' },
  { oscn_id: 16, abbreviation: 'JT', name: 'JUVENILE IN NEED OF TREATMENT' },
  { oscn_id: 57, abbreviation: 'JU', name: 'JUVENILE (LEGACY)' },
  { oscn_id: 71, abbreviation: 'MC', name: "MINISTER'S CREDENTIALS" },
  { oscn_id: 12, abbreviation: 'MH', name: 'MENTAL HEALTH' },
  { oscn_id: 33, abbreviation: 'MI', name: 'CRIMINAL MISCELLANEOUS' },
  { oscn_id: 28, abbreviation: 'ML', name: 'MARRIAGE LICENSE' },
  { oscn_id: 72, abbreviation: 'MR', name: 'MISCELLANEOUS RECEIPTS' },
  { oscn_id: 73, abbreviation: 'MRC', name: 'MISCELLANEOUS RECEIPTS - CRIMINAL' },
  { oscn_id: 74, abbreviation: 'MRCV', name: 'MISCELLANEOUS RECEIPTS - CIVIL' },
  { oscn_id: 75, abbreviation: 'MRFD', name: 'MISCELLANEOUS RECEIPTS - FAMILY DOMESTIC' },
  { oscn_id: 76, abbreviation: 'MRPB', name: 'MISCELLANEOUS RECEIPTS - PROBATE' },
  { oscn_id: 77, abbreviation: 'MRSC', name: 'MISCELLANEOUS RECEIPTS - SMALL CLAIMS' },
  { oscn_id: 36, abbreviation: 'NF', name: 'NOT FILED (CRIMINAL)' },
  { oscn_id: 41, abbreviation: 'NP', name: 'NOTARY PUBLIC (LEGACY)' },
  { oscn_id: 44, abbreviation: 'PA', name: 'PASSPORTS (LEGACY)' },
  { oscn_id: 7, abbreviation: 'PB', name: 'PROBATE' },
  { oscn_id: 9, abbreviation: 'PC', name: 'CONSERVATORSHIPS' },
  { oscn_id: 8, abbreviation: 'PG', name: 'GUARDIANSHIPS' },
  { oscn_id: 39, abbreviation: 'PH', name: 'POOL HALL' },
  { oscn_id: 13, abbreviation: 'PM', name: 'PROBATE, MISC. (LEGACY)' },
  { oscn_id: 78, abbreviation: 'PMI', name: 'PROBATE MISCELLANEOUS PROCEEDINGS' },
  { oscn_id: 34, abbreviation: 'PO', name: 'PROTECTIVE ORDER' },
  { oscn_id: 79, abbreviation: 'PP', name: 'PASSPORTS' },
  { oscn_id: 25, abbreviation: 'PS', name: 'PROCESS SERVER (LEGACY)' },
  { oscn_id: 38, abbreviation: 'PSE', name: 'PROTECTIVE SERVICES TO THE ELDERLY (LEGACY)' },
  { oscn_id: 24, abbreviation: 'PSS', name: 'PROCESS SERVER STATE' },
  { oscn_id: 10, abbreviation: 'PT', name: 'TRUSTS' },
  { oscn_id: 37, abbreviation: 'SB', name: 'STATUTORY BONDS (LEGACY)' },
  { oscn_id: 26, abbreviation: 'SC', name: 'SMALL CLAIMS' },
  { oscn_id: 23, abbreviation: 'SD', name: 'SURFACE DAMAGE' },
  { oscn_id: 19, abbreviation: 'SW', name: 'SEARCH WARRANT' },
  { oscn_id: 49, abbreviation: 'TC', name: 'TEST CASE' },
  { oscn_id: 43, abbreviation: 'TL', name: 'TAX LIENS' },
  { oscn_id: 80, abbreviation: 'TM', name: 'TRANSIENT MERCHANT LICENSE' },
  { oscn_id: 18, abbreviation: 'TR', name: 'TRAFFIC' },
  { oscn_id: 50, abbreviation: 'TRI', name: 'TRAFFIC- FILED BY INFORMATION (LEGACY)' },
  { oscn_id: 30, abbreviation: 'WH', name: 'WRIT (HABEAS)' },
  { oscn_id: 81, abbreviation: 'WIL', name: 'FILING OF WILLS' },
  { oscn_id: 20, abbreviation: 'WL', name: 'WILDLIFE' },
  { oscn_id: 82, abbreviation: 'YO', name: 'YOUTHFUL OFFENDER' }
]

case_types.each do |case_type|
  CaseType.find_or_create_by!(case_type)
end
