name: Run RSpec

on: [push]

jobs:
  build:
    name: Run rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Bundle install
        run: bundle install
      - name: Run rubocop
        run: |
          bundle exec rubocop
